language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"

install: source build_tools/travis/install.sh

script:
  - if [ ${COVERAGE} == "true" ];
    then pytest --cov=skopt --durations=10; else
    pytest --durations=10;
    fi

after_success:
  - if [ ${COVERAGE} == "true" ]; then
    pip install codecov;
    codecov;
    fi

deploy:
  provider: pypi
  user: mimba
  password:
    secure: "VgrP/BM1TnUR7uZvOpCbE/rkywhz/Zb2HGPxP6tKqiuwFi/uZ6/Ei5dgInKiobRaXu3ciMhQF0pigO0rrO5Ya4t/G2XX928RVOhgj5au87ZGIOGspeVysrvairreiU91QfwmVVZmYhOfeaRnEQ5COAQgXWPaWgF1NCVTtSa8WChW+AvYoVvyRMZ+1V3jOx4qhqqhyr8fyYl5Kh3o2hc+1xZiJRwdidRTEm/PV/XGqPwyEdCUcRSY8mCQjHMXLFDX9n7F1hJDYpAWAalfSfCcWdpiZTwvNwWY4LZnKzHDlMA434bRwxWGsDg/LAli6/R7VMK0zAot41IO9Ay1KWvsPZg7gA1E4fWeSlbl4XWHCS0lU7M7WX90ZlLYElrL8/PnUXT+Ly8HVp/AWjTb78AUlWmVozdpMCNze5erVDdcbSmLpKf7Zx5V7aof7S//hfjoiEE3Zx6NSF4+nNo8KOqk6W80vWHVq/hLgEEM3nY9TaK9u7MRig2a6jHzqGRN6jeMIBx13CQSQB6zHv6C4KmoupPNbzadt3t3OEvm5t78N9q/h/GMzK+ocN+bNNSez/y/A/oDA1GvT1I5XBtMXyFqfmfmVkp7KmTd89jzgymHzip/GH/KmDAWUfwq3Z7yWg+Suuc+efGycOBice8ZGfBqjACloidbMMrRGz8bjK9u0pY="
  # this line together with `setup.cfg` creates universal wheels as long as
  # skopt is a python only module (no compiled code)
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: mimba/scikit-optimize
    condition: "$PYTHON_VERSION = 3.6"
