language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"

install: source build_tools/travis/install.sh

script:
  - if [ ${COVERAGE} == "true" ];
    then pytest --cov=skopt --durations=10; else
    pytest --durations=10;
    fi

after_success:
  - if [ ${COVERAGE} == "true" ]; then
    pip install codecov;
    codecov;
    fi

deploy:
  provider: pypi
  user: mimba
  password:
    # create the deployment password
    # travis logout
    # travis login
    # travis encrypt <MIMBA_PYPI_PASSWORD>
    secure: "LsqvGSCNwC+yciI90u3nKkYtYBGZoMdtRRdwHPPv0jqT6FLrr2M/84Cq2T+WrkZjO3A+Ei6eD5yHzhw55xJUy4XY7sjQU7EXD4XIDvZTlvxSkort/nqk3yt4boCaXApecoGqGHmqDZO5fguV9ECMdXnzvO043QDE1zXj7CY4x4jiQ9GPY6CwTNLq6Qt4RBR86gx/rcEGgqNy4mKBe9PKiRLJ4CfTCES4+wU0cZIzPMyQ4EX40F9DdKcDjesscLQaw++zfhGf/mAa8MeG1suz+Rs8XVuTw4eYTyCQD9m5SpVN7Dfg/jeAo0eHumMwQDlUjOb1kqfHwYvq9mI/J3psAcAv+SF342+dFXYH1zauOIKIcpe9kCSOpXYh63PdJJ28oodIY+ECvjyavfHkU7POFOBM5ogRih2bX/UoEyb2S4KgLGotj6mH4NSG/BS6Fl8PBrb1m81aNEXAWLeXd9m3vYIqQ0LzgT4/gMKadYpPZSijSrzg8rptKFQz64juG1JMQ5MLTD3wBcNfcSq3FzNAly0/fEYNH8Q5QOqrtpRxePfL4seI0PfRMkGR9ps6/yvsspQwpmIAQrmUVafjDgBYQNBh42rpb9Ia0liRY8H+2kMpym7UOfvj4VjHTbIwDjhV+7HoL8OHqfDVkA38N8jSh1ICwaSLPBUft/lUXyDw0+Q="
  # this line together with `setup.cfg` creates universal wheels as long as
  # skopt is a python only module (no compiled code)
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: mimba/scikit-optimize
    condition: "$PYTHON_VERSION = 3.6"
