language: python

notifications:
  email: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/skopt
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    - name: "Python 3.7 - scikit 0.22.2.post1"
      python: "3.7"
      env: DISTRIB="conda" PYTHON_VERSION="3.7"
        NUMPY_VERSION="1.18.3" SCIPY_VERSION="1.4.1" PYAML_VERSION="17.8.0"
        SCIKIT_LEARN_VERSION="0.22.2.post1" MATPLOTLIB_VERSION="*" COVERAGE="true"
        JOBLIB_VERSION="0.14.1"

install: source build_tools/travis/install.sh
script:
  - bash build_tools/travis/test_script.sh
  - bash build_tools/travis/test_docs.sh
after_success: source build_tools/travis/after_success.sh

deploy:
  provider: pypi
  user: mimba
  password:
    # create the deployment password
    # travis logout
    # travis login
    # travis encrypt <MIMBA_PYPI_PASSWORD>
    secure: "LsqvGSCNwC+yciI90u3nKkYtYBGZoMdtRRdwHPPv0jqT6FLrr2M/84Cq2T+WrkZjO3A+Ei6eD5yHzhw55xJUy4XY7sjQU7EXD4XIDvZTlvxSkort/nqk3yt4boCaXApecoGqGHmqDZO5fguV9ECMdXnzvO043QDE1zXj7CY4x4jiQ9GPY6CwTNLq6Qt4RBR86gx/rcEGgqNy4mKBe9PKiRLJ4CfTCES4+wU0cZIzPMyQ4EX40F9DdKcDjesscLQaw++zfhGf/mAa8MeG1suz+Rs8XVuTw4eYTyCQD9m5SpVN7Dfg/jeAo0eHumMwQDlUjOb1kqfHwYvq9mI/J3psAcAv+SF342+dFXYH1zauOIKIcpe9kCSOpXYh63PdJJ28oodIY+ECvjyavfHkU7POFOBM5ogRih2bX/UoEyb2S4KgLGotj6mH4NSG/BS6Fl8PBrb1m81aNEXAWLeXd9m3vYIqQ0LzgT4/gMKadYpPZSijSrzg8rptKFQz64juG1JMQ5MLTD3wBcNfcSq3FzNAly0/fEYNH8Q5QOqrtpRxePfL4seI0PfRMkGR9ps6/yvsspQwpmIAQrmUVafjDgBYQNBh42rpb9Ia0liRY8H+2kMpym7UOfvj4VjHTbIwDjhV+7HoL8OHqfDVkA38N8jSh1ICwaSLPBUft/lUXyDw0+Q="
  # this line together with `setup.cfg` creates universal wheels as long as
  # skopt is a python only module (no compiled code)
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: mimba/scikit-optimize
    condition: "$PYTHON_VERSION = 3.7"
